### ISSUE TITLE
[Website] Layout has errors

### ISSUE THREAD

**Issue by cptchuckles** [cptchuckles/SharpScape#18]
1.) The main `<article>` element of the forum index page (when visiting `/forum`) is too wide and creates a horizontal scrollbar in desktop form-factor.  Main page body should never scroll horizontally.  This is caused by something in the layout.

2.) Some navbar buttons at the top don't have consistent styles.  They sit too far apart in desktop form factor, and in mobile form factor they are different widths.
(this is probably because the outermost div of the nav menu is duplicated, instead of putting the Forum button's `nav-item` div inside the next to the Home button's `nav-item` div.  Also `px-3` should be removed)

3.) In the forum index, **SharpScape** is misspelled on the forum index: it says *SharpShade*

4.) In the forum index, forum topic links are dead links.  Tasks should **not** include dead links or broken features.  The links' `href` values should be removed until there is something for them to point to (that is, when #11 is closed)
**Edit:** We should probably just make a nice looking "Under Construction" page for links that *should* go somewhere, but where there's nowhere to go yet. I'll open another issue for that feature.

~~Admittedly, these are things I should have checked in #17 before merging it.  I will be more vigilant in the future.~~

**Comment by SunnyRo** [comment]
1. Thats belong to the css file because it uses px for some element now and people's monitors have different resolutions. I will look it to that later. Right now we just setup the basic its not the final looks.
2. Same problem with the css file. Also I dont write css for mobile view yet. Mobile view
4. Forum topic links are just place holder now because I havent made the topic index. again task #10 just to make the forum index (the view). link href will be a parameter later when Im done the topic index.

**Comment by SunnyRo** [comment]
Also if you can post the screenshot of the problems It would help a lots because Its hard to me to find the problems since it looks okay on screen (css again).
